FROM ros:jazzy-ros-base

RUN apt update
RUN apt -y upgrade

RUN curl -L https://download.eclipse.org/zenoh/debian-repo/zenoh-public-key | sudo gpg --dearmor --yes --output /etc/apt/keyrings/zenoh-public-key.gpg


RUN echo "deb [signed-by=/etc/apt/keyrings/zenoh-public-key.gpg] https://download.eclipse.org/zenoh/debian-repo/ /" | sudo tee -a /etc/apt/sources.list > /dev/null

RUN sudo apt update


RUN apt -y install zenoh-bridge-ros2dds ros-jazzy-rmw-cyclonedds-cpp